language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Kv49XzSD/OIWyXkmLx3O8Nv3I5fm2ddK6efCKNyAvZ5TNRsUqfp5Jq2ljboYDDKMS+EFU9ie2lmLGzn3hvQWwm5Aesoms5xGjaeZ2dzLW1foiZ2+WphUXzqRNDGXIHR36G0dpQPSNoCtH1ajMDtoRJrbQxs0FhqYEb5kjHXG2MJ/yDvGyz3QmvUtJwHBr97jZIPc+LXX1MXM4N9nklvC5byEmT8/Ui5ISl37rtq3Mfv/bvUpoDXmB2CHW15h8NwmAcfhmhAoRkGizfdOqTwluzCuvWB2OCn/qJaZqi39tif2Zw1NtV/WLcFeL3ByJNAbTtEiQaiCIrJc18KFrQIg/pxc18XXzQvTrN7bc2CDc+WrfRO9FSve3Is/ivOkwQ/H6K30O3A53wmoEwbshR63hITm46greIgdXdWFMvlfJJmSVjHSVm6on17TMuqVtqRVdQUVTIs/WtCX+W7VYMFdLKzXwt1SgSecDMv1mg9pFhuoVLKlTYvjHZ1LAzXetWwwy4MVO7tBnmtlDF2lwG5epA8LY389tzx9riyJDpAdR5IZD4skLfOX4/133jTQ5PvPX5E83LLzvoE15pFDjki8AiDkN7eJNnLzVeIwqftqP/zZkkMPzEjwsaS6WKHS/FYWoCaE41ctd22Xp7ptTIGUFSUhL3hEArxA5CyNGecZs64=
  on:
    branch: master
    tags: true
#dd:
#  secure: Kv49XzSD/OIWyXkmLx3O8Nv3I5fm2ddK6efCKNyAvZ5TNRsUqfp5Jq2ljboYDDKMS+EFU9ie2lmLGzn3hvQWwm5Aesoms5xGjaeZ2dzLW1foiZ2+WphUXzqRNDGXIHR36G0dpQPSNoCtH1ajMDtoRJrbQxs0FhqYEb5kjHXG2MJ/yDvGyz3QmvUtJwHBr97jZIPc+LXX1MXM4N9nklvC5byEmT8/Ui5ISl37rtq3Mfv/bvUpoDXmB2CHW15h8NwmAcfhmhAoRkGizfdOqTwluzCuvWB2OCn/qJaZqi39tif2Zw1NtV/WLcFeL3ByJNAbTtEiQaiCIrJc18KFrQIg/pxc18XXzQvTrN7bc2CDc+WrfRO9FSve3Is/ivOkwQ/H6K30O3A53wmoEwbshR63hITm46greIgdXdWFMvlfJJmSVjHSVm6on17TMuqVtqRVdQUVTIs/WtCX+W7VYMFdLKzXwt1SgSecDMv1mg9pFhuoVLKlTYvjHZ1LAzXetWwwy4MVO7tBnmtlDF2lwG5epA8LY389tzx9riyJDpAdR5IZD4skLfOX4/133jTQ5PvPX5E83LLzvoE15pFDjki8AiDkN7eJNnLzVeIwqftqP/zZkkMPzEjwsaS6WKHS/FYWoCaE41ctd22Xp7ptTIGUFSUhL3hEArxA5CyNGecZs64=
